Python Setup and Packages

diff --git a/install b/install
--- a/install
+++ b/install
@@ -330,3 +330,99 @@ INSERT INTO data (value) VALUES ('~/Library/Mobile Documents/com~apple~CloudDocs
 INSERT INTO preferences (key, data_id, picture_id) VALUES (1, 1, 1); \
 \""
 run killall Dock
+
+###############################################################################
+# Python Setup                                                                #
+###############################################################################
+
+# Removed user's cached credentials
+# This script might be run with .dots, which uses elevated privileges
+sudo -K
+
+echo "------------------------------"
+echo "Setting up pip."
+
+# Install pip
+easy_install pip
+
+###############################################################################
+# Virtual Enviroments                                                         #
+###############################################################################
+
+echo "------------------------------"
+echo "Setting up virtual environments."
+
+# Install virtual environments globally
+# It fails to install virtualenv if PIP_REQUIRE_VIRTUALENV was true
+export PIP_REQUIRE_VIRTUALENV=false
+pip install virtualenv
+pip install virtualenvwrapper
+
+echo "------------------------------"
+echo "Source virtualenvwrapper from ~/.extra"
+
+EXTRA_PATH=~/.extra
+echo $EXTRA_PATH
+echo "" >> $EXTRA_PATH
+echo "" >> $EXTRA_PATH
+echo "# Source virtualenvwrapper, added by pydata.sh" >> $EXTRA_PATH
+echo "export WORKON_HOME=~/.virtualenvs" >> $EXTRA_PATH
+echo "source /usr/local/bin/virtualenvwrapper.sh" >> $EXTRA_PATH
+echo "" >> $BASH_PROFILE_PATH
+source $EXTRA_PATH
+
+###############################################################################
+# Python 2 Virtual Enviroment                                                 #
+###############################################################################
+
+echo "------------------------------"
+echo "Setting up py2-data virtual environment."
+
+# Create a Python2 data environment
+mkvirtualenv py2-data
+workon py2-data
+
+# Install Python data modules
+step "Install Python 2 Module\n"
+
+for package in $(<$cwd/.stack/pip2); do
+    if ! pip install list -1 | grep -q "^${package}\$"; then
+run pip install install $package
+    fi
+done
+
+###############################################################################
+# Python 3 Virtual Enviroment                                                 #
+###############################################################################
+
+echo "------------------------------"
+echo "Setting up py3-data virtual environment."
+
+# Create a Python3 data environment
+mkvirtualenv --python=/usr/local/bin/python3 py3-data
+workon py3-data
+
+# Install Python data modules
+step "Install Python 3 Module\n"
+
+for package in $(<$cwd/.stack/pip3); do
+    if ! pip install list -1 | grep -q "^${package}\$"; then
+run pip install install $package
+    fi
+done
+
+###############################################################################
+# Install IPython Profile
+###############################################################################
+
+echo "------------------------------"
+echo "Installing IPython Notebook Default Profile"
+
+# Add the IPython profile
+mkdir -p ~/.ipython
+cp -r init/profile_default/ ~/.ipython/profile_default
+
+echo "------------------------------"
+echo "Script completed."
+echo "Usage: workon py2-data for Python2"
+echo "Usage: workon py3-data for Python3"
